services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=pg
      - ADMINER_DESIGN=dracula
    ports:
      - "7080:8080"
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - qcontrol_network

networks:
  qcontrol_network:
    external: true
