services:
  pg:
    image: postgres:16.4
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - "5432"
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_wDB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - qcontrol_network

networks:
  qcontrol_network:
    external: true

volumes:
  pgdata:
