services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - "6379"
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qcontrol_network
networks:
  qcontrol_network:
    external: true
volumes:
  redis-data:
